### ISSUE TITLE
Ask for help: recsys-challenge-2016 dataset XING

### ISSUE THREAD

**Issue by mengxiangjialzh** [squall-1002/xing_jobs_reco#1]
Hi， I'm reproducing a paper with the XING dataset , do you still keep the original dataset and would you please share it with me?
thank u very much..............

**Comment by squall-1002** [comment]
Hi @mengxiangjialzh ,
unfortunately, I am not allowed to share the dataset. It's a pity that XING doesn't share the dataset publicly as it would really enrich the recsys datasets available for research.
Maybe try contacting Fabian Abel directly, who was responsible for it back then.
